#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/llvm-gcc -DOPENSSL_THREADS -D_REENTRANT -arch armv7 -O3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk -fomit-frame-pointer -fno-common -I/usr/local/ssl/Release-iphoneos/include"
  #define PLATFORM "iphoneos-cross"
  #define DATE "Wed Jun 26 12:34:27 EDT 2013"
#endif
